// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-OlhBCDQYcbfVbqZv0w4xs7HnHrrSdag',
    appId: '1:603966182516:web:335a2e8c2656c5024aad21',
    messagingSenderId: '603966182516',
    projectId: 'financeapp-189b7',
    authDomain: 'financeapp-189b7.firebaseapp.com',
    storageBucket: 'financeapp-189b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgIqPFtoojUfOtzbOXg8cXCCrCKKcFtqQ',
    appId: '1:603966182516:android:21e7490f6337167d4aad21',
    messagingSenderId: '603966182516',
    projectId: 'financeapp-189b7',
    storageBucket: 'financeapp-189b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASQvsj75sRo89U1N9-PINubsjE-RRRL6I',
    appId: '1:603966182516:ios:297ae558fd3f8ad54aad21',
    messagingSenderId: '603966182516',
    projectId: 'financeapp-189b7',
    storageBucket: 'financeapp-189b7.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASQvsj75sRo89U1N9-PINubsjE-RRRL6I',
    appId: '1:603966182516:ios:297ae558fd3f8ad54aad21',
    messagingSenderId: '603966182516',
    projectId: 'financeapp-189b7',
    storageBucket: 'financeapp-189b7.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-OlhBCDQYcbfVbqZv0w4xs7HnHrrSdag',
    appId: '1:603966182516:web:658c2ac4a9e893064aad21',
    messagingSenderId: '603966182516',
    projectId: 'financeapp-189b7',
    authDomain: 'financeapp-189b7.firebaseapp.com',
    storageBucket: 'financeapp-189b7.firebasestorage.app',
  );
}
